# Generated by Django 6.0 on 2026-02-23 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.CharField(max_length=50)),
                ('ProductName', models.CharField(max_length=200)),
                ('Category', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StoreOwneres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storename', models.CharField(max_length=100)),
                ('ownername', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrentStock', models.IntegerField()),
                ('ForecastSevendays', models.FloatField()),
                ('RecommendedOrder', models.FloatField()),
                ('RiskLevel', models.CharField(max_length=20)),
                ('Confidence', models.FloatField(blank=True, null=True)),
                ('GeneratedAt', models.DateTimeField(auto_now_add=True)),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.storeowneres')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('QuantitySold', models.IntegerField()),
                ('PriceAtSale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.storeowneres')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.storeowneres'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('store', 'ProductID')},
        ),
        migrations.CreateModel(
            name='UploadedFileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileHash', models.CharField(max_length=255)),
                ('UploadedAt', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.storeowneres')),
            ],
            options={
                'unique_together': {('store', 'FileHash')},
            },
        ),
    ]
